import {classicHandles,classicHandleRadius} from './experimental.js';
export function handleRadius(style,t,p,a){const r=p.stemDiameter/2,flare=p.handleFlare*.09,c=p.complexity/100;let base=r;if(style==='straight')base=r*(1-.08*t);if(style==='flared')base=r*(.8+.45*t*t+flare*t);if(style==='mushroom')base=r*(.78+(.8+flare)*Math.pow(Math.sin(Math.PI*t/2),5));if(style==='twisted')base=r*(.86+.18*Math.sin(a*3+p.handleTwist*t));if(style==='crown')base=r*(.8+.38*t*t);if(style==='spire')base=r*(1.02-.42*t+.34*Math.sin(Math.PI*t));if(style==='chalice')base=r*(.74+.62*Math.pow(Math.abs(2*t-1),1.7)+flare*t);if(style==='vine')base=r*(.78+.14*Math.sin(a*3+p.handleTwist*t*1.4)+.18*Math.sin(Math.PI*t));if(style==='winged')base=r*(.76+.18*Math.sin(Math.PI*t));const fins=p.handleFins?Math.pow(Math.max(0,Math.cos(a*p.handleFins+p.handleTwist*t*.35)),7)*p.handleFlare*.17*Math.sin(Math.PI*t):0;let pommel=0;if(t>.72&&p.topperStyle==='none'){const u=(t-.72)/.28;if(p.pommelStyle==='orb')pommel=r*.65*Math.sin(Math.PI*u);if(p.pommelStyle==='crystal')pommel=r*.62*(1-Math.abs(2*u-1));if(p.pommelStyle==='flame')pommel=r*.5*Math.sin(Math.PI*u)*(1-u*.55);if(p.pommelStyle==='crown')pommel=r*.5*Math.pow(Math.max(0,Math.cos(a*Math.max(4,p.handleFins))),6)*u;}if(classicHandles.includes(style)){base=classicHandleRadius(style,t,r,a);pommel=0;}const fancy=Math.max(r*.45,base+fins+pommel);return r+(fancy-r)*c;}
export function topperRadius(p,t,a){const W=p.topperWidth/2,f=p.topperFeatures,phase=a*f+p.topperTwist*t*.25,rel=p.topperRelief;let r;if(p.topperStyle==='mushroom'){r=t<.48?W*.32:W*Math.pow(Math.max(0,Math.sin((t-.45)/.55*Math.PI)),.42);if(t>.92)r*=Math.max(0,(1-t)/.08);}else if(p.topperStyle==='robot'){r=W*(t<.14?.55:t<.72?1:t<.88?.74:Math.max(0,(1-t)/.12)*.74);r+=rel*.22*Math.pow(Math.abs(Math.cos(phase)),10);}else if(p.topperStyle==='ghost'){r=W*(.72+.18*Math.sin(Math.PI*t))*(1-Math.pow(t,7));if(t<.2)r+=rel*.35*Math.sin(phase);}else if(p.topperStyle==='crystal'){r=W*(t<.68?.58+.42*t/.68:Math.max(0,(1-t)/.32));r+=rel*.28*Math.abs(2/Math.PI*Math.asin(Math.sin(phase)));}else if(p.topperStyle==='skull'){const cranium=.36+.72*Math.exp(-Math.pow((t-.68)/.27,2)),jaw=t<.42?.24*(1-t/.42):0;r=W*(cranium+jaw)*(1-Math.pow(t,9));if(t<.34)r+=rel*.26*Math.pow(Math.max(0,Math.cos(phase)),8);if(t>.38&&t<.7)r-=rel*.18*Math.pow(Math.max(0,Math.cos(phase)),6);}else{r=W*Math.pow(Math.max(0,Math.sin(Math.PI*t)),.43);r-=rel*.16*Math.pow(Math.max(0,Math.cos(phase)),8)*Math.sin(Math.PI*t);}return Math.max(0,r);}
export function integratedTotemRadius(p,t,a,joinRadius){let raw=topperRadius(p,t,a);const phase=a*Math.max(3,p.topperFeatures)+p.topperTwist*t*.28,envelope=Math.sin(Math.PI*t);if(p.topperStyle==='trident')raw*=.82+.34*Math.pow(Math.max(0,Math.cos(a*3)),4);if(p.topperStyle==='coral')raw*=.86+.24*Math.pow(Math.max(0,Math.cos(phase)),4);if(p.topperStyle==='tentacle')raw*=.9+.16*Math.sin(phase);if(p.topperStyle==='cyclops')raw*=.9+.12*Math.cos(a*2)*envelope;if(t>.92)raw*=Math.max(0,(1-t)/.08);const u=Math.min(1,t/.18),blend=u*u*(3-2*u);return Math.max(0,joinRadius*(1-blend)+raw*blend);}

// Atlantis's original notched fluke outline, sampled as a rounded solid field
// so it can be unioned with the new open bodies rather than exported separately.
export function dolphinTailField(THREE,p,gripTop,zone){
 const width=Math.max(15,Math.min(p.topperWidth,22))*Math.max(.72,p.complexity/100),s=width/20,shape=new THREE.Shape();
 shape.moveTo(0,-3*s);shape.bezierCurveTo(-1.8*s,-1.2*s,-4.6*s,.5*s,-9.4*s,2.7*s);shape.bezierCurveTo(-10.8*s,3.4*s,-10.8*s,5.7*s,-9.8*s,7.2*s);shape.bezierCurveTo(-6.2*s,6.7*s,-2.8*s,5.6*s,0,3.1*s);shape.bezierCurveTo(2.8*s,5.6*s,6.2*s,6.7*s,9.8*s,7.2*s);shape.bezierCurveTo(10.8*s,5.7*s,10.8*s,3.4*s,9.4*s,2.7*s);shape.bezierCurveTo(4.6*s,.5*s,1.8*s,-1.2*s,0,-3*s);shape.closePath();
 const polygon=shape.getPoints(12).map(q=>[q.x,gripTop-.8+(q.y/s+3)/10.2*(zone+.2)]),depth=Math.max(2.8,p.stemDiameter*.38)/2,round=.5;
 return {bounds:[-width*.6-1,width*.6+1,gripTop-2,gripTop+zone+1,-depth-1,depth+1],fn(x,y,z){let distance=Infinity,inside=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[j],b=polygon[i],dx=b[0]-a[0],dy=b[1]-a[1],ll=dx*dx+dy*dy,t=ll?Math.max(0,Math.min(1,((x-a[0])*dx+(y-a[1])*dy)/ll)):0;distance=Math.min(distance,Math.hypot(x-a[0]-t*dx,y-a[1]-t*dy));if((a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])inside=!inside;}const q=(inside?-distance:distance),w=Math.abs(z)-(depth-round);return Math.hypot(Math.max(q,0),Math.max(w,0))+Math.min(Math.max(q,w),0)-round;}};
}
