import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.TOPBOT_PLAYWRIGHT_MODULE || 'playwright');
export async function runBrowserTests(base,adminCode) {
 const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-unsafe-swiftshader']});
 const errors=[];
 try {
  const admin=await browser.newContext({acceptDownloads:true});
  const student=await browser.newContext();
  const a=await admin.newPage(),s=await student.newPage();
  for(const page of [a,s])page.on('pageerror',error=>errors.push(error.message));
  await a.goto(base);await a.locator('#manualMode').click();
  await a.locator('#openPrintRoom').click();
  await a.locator('#adminAccessCode').fill(adminCode);await a.locator('#adminAccessSubmit').click();
  await a.locator('#printRoomMessage').filter({hasText:'Up to date.'}).waitFor();
  const initialCount=Number(await a.locator('#adminClassCount').textContent());
  await a.locator('#showAddClass').click();
  await a.locator('#newSchoolName').fill('Browser School');
  await a.locator('#createClass').click();
  await a.locator('#detailClassName').filter({hasText:'Browser School'}).waitFor();
  assert.equal(Number(await a.locator('#adminClassCount').textContent()),initialCount+1);
  const classCode=(await a.locator('#detailClassCode').textContent()).trim();
  await a.locator('#backToClasses').click();
  const card=a.locator('.class-card').filter({hasText:'Browser School'});
  await card.getByRole('button',{name:'Archive school',exact:true}).click();
  await a.locator('#printRoomMessage').filter({hasText:'School archived.'}).waitFor();
  assert.equal(await a.locator('.class-card').filter({hasText:'Browser School'}).count(),0);
  assert.equal(Number(await a.locator('#adminClassCount').textContent()),initialCount);
  await a.locator('#schoolListMode').selectOption('archived');
  assert.equal(await a.locator('.class-card').filter({hasText:'Browser School'}).count(),1);
  await s.goto(base);await s.locator('#manualMode').click();
  await s.locator('#topSavePanel summary').click();
  await s.locator('#classCode').fill(classCode);await s.locator('#studentName').fill('Browser Student');
  await s.locator('#saveTop').click();
  await s.locator('#topSaveMessage').filter({hasText:'archived'}).waitFor();
  await a.locator('.class-card').filter({hasText:'Browser School'}).getByRole('button',{name:'Restore school'}).click();
  await a.locator('#printRoomMessage').filter({hasText:'School restored'}).waitFor();
  assert.equal(Number(await a.locator('#adminClassCount').textContent()),initialCount+1);
  assert.match(await s.locator('#filamentChoice option[value=pastel]').textContent(),/Glow in the dark rainbow/);
  await s.locator('#saveTop').click();
  await s.locator('#topSaveResult:not(.hidden)').waitFor();
  const code=(await s.locator('#savedTopCode').textContent()).trim();
  assert.match(code,/^[23456789ABCDEFGHJKLMNPQRSTUVWXYZ]{5}$/);
  await a.locator('#schoolListMode').selectOption('active');
  await a.locator('#refreshPrintRoom').click();
  await a.locator('#printRoomMessage').filter({hasText:'Up to date.'}).waitFor();
  await a.locator('.class-card').filter({hasText:'Browser School'}).getByRole('button',{name:'View tops'}).click();
  const row=a.locator('.admin-top-row').filter({hasText:code});
  await row.getByRole('button',{name:'✓ Printed',exact:true}).click();
  await row.locator('.admin-top-status').filter({hasText:'printed'}).waitFor();
  await row.locator('input[type="checkbox"]').check();
  const downloadPromise=a.waitForEvent('download');
  await a.locator('#downloadSelectedTops').click();
  const download=await downloadPromise;assert(download.suggestedFilename().endsWith('.stl'));assert(download.suggestedFilename().includes('Glow-in-the-dark-rainbow'));assert.equal(await download.failure(),null);
  await row.getByRole('button',{name:'🗑 Trash',exact:true}).click();
  await row.waitFor({state:'detached'});
  await a.locator('#openTrash').click();
  await a.locator('.trash-top-row').filter({hasText:code}).getByRole('button',{name:'↶ Restore'}).click();
  await a.locator('.trash-top-row').filter({hasText:code}).waitFor({state:'detached'});
  await a.locator('#lockPrintRoom').click();
  await a.locator('#openPrintRoom').click();
  await a.locator('#adminAccessGate:not([hidden])').waitFor();
  await a.keyboard.press('Escape');
  assert.equal(await a.locator('#adminAccessGate').isVisible(),false);
  assert.deepEqual(errors,[]);
  console.log('PASS: two isolated browser contexts, add/archive/restore, cross-browser submission, refresh, printed state, batch STL generation/download, Trash restore, lock and Escape; no browser errors.');
 } finally {await browser.close();}
}
