'use client';

import { useEffect, useMemo, useState } from 'react';

type Waveform={source:'live'|'unavailable';channel?:string;sampleRate?:number;sampleCount?:number;end?:string;points?:number[]};
const demoPoints=(seed:string)=>Array.from({length:180},(_,i)=>{const n=seed.split('').reduce((sum,c)=>sum+c.charCodeAt(0),0);const pulse=Math.exp(-Math.pow((i-105)/23,2));return Math.sin(i*.31+n)*.07+Math.sin(i*1.71+n*.2)*.025+pulse*Math.sin(i*1.08)*.62});
const line=(points:number[],width=300,height=72)=>points.map((value,index)=>`${(index/(points.length-1||1))*width},${height/2-value*(height*.42)}`).join(' ');
const displayPoints=(values:number[],autoGain:boolean,target=720)=>{const mean=values.reduce((sum,value)=>sum+value,0)/(values.length||1),centred=values.map(value=>value-mean),reduced:number[]=[];if(centred.length<=target)reduced.push(...centred);else{const bucket=centred.length/Math.ceil(target/2);for(let start=0;start<centred.length;start+=bucket){const slice=centred.slice(Math.floor(start),Math.min(centred.length,Math.floor(start+bucket)));if(slice.length)reduced.push(Math.min(...slice),Math.max(...slice))}}const absolute=reduced.map(Math.abs).sort((a,b)=>a-b),scale=autoGain?Math.max(...absolute,1):(absolute[Math.floor(absolute.length*.985)]||1);return reduced.slice(0,target).map(value=>Math.max(-1,Math.min(1,value/scale)))};

export default function LiveWaveform({network,station,eventTime,autoGain=true}:{network:string;station:string;eventTime?:string;autoGain?:boolean}){
 const [data,setData]=useState<Waveform|null>(null);const [loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;const load=async()=>{setLoading(true);try{const eventQuery=eventTime?`&eventTime=${encodeURIComponent(eventTime)}`:'';const response=await fetch(`/api/waveform?network=${encodeURIComponent(network)}&station=${encodeURIComponent(station)}${eventQuery}`);if(!response.ok||!response.headers.get('content-type')?.includes('mseed'))throw new Error();const {miniseed}=await import('seisplotjs'),records=miniseed.parseDataRecords(await response.arrayBuffer()).sort((a,b)=>a.header.startTime.toMillis()-b.header.startTime.toMillis()),samples=records.flatMap(record=>Array.from(record.decompress()));if(!samples.length)throw new Error();if(active)setData({source:'live',channel:response.headers.get('X-QuakeQuest-Channel')||records[0].header.chanCode,sampleRate:records[0].header.sampleRate,sampleCount:samples.length,end:response.headers.get('X-QuakeQuest-End')||undefined,points:displayPoints(samples,autoGain)})}catch{if(active)setData({source:'unavailable'})}finally{if(active)setLoading(false)}};load();if(eventTime)return()=>{active=false};const timer=setInterval(load,60000);return()=>{active=false;clearInterval(timer)}},[network,station,eventTime,autoGain]);
 const points=useMemo(()=>data?.source==='live'&&data.points?.length?data.points:eventTime?Array(180).fill(0):demoPoints(`${network}.${station}`),[data,network,station,eventTime]);const isLive=data?.source==='live',eventMode=Boolean(eventTime);
 return <section className="live-waveform" aria-label={`${eventMode?'Event-time':'Latest hour of'} waveform data from ${station}`}><header><b><i className={isLive?'live':''}/>{loading?'CONTACTING BGS…':isLive?(eventMode?'REAL BGS WAVEFORM · AROUND EVENT TIME':'REAL BGS WAVEFORM · LATEST HOUR'):(eventMode?'NO EVENT-TIME TRACE RETURNED':'DEMO TRACE · BGS DATA UNAVAILABLE')}</b>{isLive&&<span>{data.channel} · {data.sampleRate} samples/sec</span>}</header><svg viewBox="0 0 300 72" role="img" aria-label={isLive?'BGS seismic measurements':eventMode?'No event-time waveform available':'Demonstration seismic trace'} preserveAspectRatio="none"><path d="M0 36H300"/><polyline points={line(points)}/></svg><footer><span>{isLive?`${data.sampleCount?.toLocaleString()} genuine samples, compressed for display`:eventMode?'BGS returned no vertical-channel data for this station and time':'A safe example—not a live measurement'}</span><span>{isLive&&data.end?new Date(data.end).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',timeZone:'UTC'})+' UTC':''}</span></footer>{isLive&&(autoGain?<small className="wave-gain-note"><b>AUTO-GAIN ON</b> · Enlarged to fit. Timing and relative peaks within this trace are preserved; height cannot be compared with another station.</small>:<small className="wave-gain-note raw"><b>LAST-HOUR OVERVIEW</b> · Restored display scaling makes ordinary ground movement visible. Heights are not comparable between stations.</small>)}{eventMode&&<small className="event-wave-note">A real BGS recording from 15 seconds before to 105 seconds after the listed origin time. It is not an official station–event association.</small>}</section>;
}
